# Generated by Django 4.2.7 on 2023-11-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_sponsor_sponsorship_sponsorship_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa Sprzętu', max_length=50, null=True, unique=True)),
                ('producer', models.CharField(help_text='Nazwa producenta', max_length=50, null=True)),
                ('all_quantity', models.PositiveSmallIntegerField(help_text='Ilość sprzętu', null=True)),
                ('description', models.TextField(blank=True, help_text='Specyfikacja sprzętu', null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Imię', max_length=60, null=True)),
                ('surname', models.CharField(blank=True, help_text='Nazwisko', max_length=60, null=True)),
                ('club', models.ManyToManyField(to='clubs.club')),
            ],
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(help_text='Nazwa Sponsora', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Player_data',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clubs.players')),
                ('pesel', models.CharField(blank=True, help_text='Pesel', max_length=11, null=True, unique=True)),
                ('extranet', models.CharField(blank=True, help_text='nr extranet', max_length=7, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Data urodzenia', null=True)),
                ('place_of_birth', models.CharField(blank=True, help_text='Miejsce urodzenia', max_length=60, null=True)),
                ('addres', models.CharField(blank=True, help_text='Adres zamieszkania', max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rented_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(help_text='Ilość pożyczonego sprzętu', null=True)),
                ('date_of_rental', models.DateField(help_text='Data wypożyczenia', null=True)),
                ('date_of_return', models.DateField(blank=True, help_text='Data zwrócenia', null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.equipment')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.players')),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='equipment',
            field=models.ManyToManyField(through='clubs.Rented_equipment', to='clubs.equipment'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa Obiektu', max_length=60, null=True)),
                ('addres', models.CharField(blank=True, help_text='Adres obiektu', max_length=60, null=True)),
                ('lights', models.BooleanField(blank=True, help_text='Oświetlenie', null=True)),
                ('surface', models.CharField(choices=[('1', 'murawa naturalna'), ('2', 'murawa sztuczna'), ('3', 'parkiet')], default='1')),
                ('description', models.TextField(blank=True, help_text='Specyfikacja obiektu', null=True)),
                ('club', models.ManyToManyField(to='clubs.club')),
            ],
        ),
    ]
