# Generated by Django 4.2.7 on 2023-11-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_equipment_players_alter_sponsor_name_player_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(blank=True, help_text='Obecny na zajęciach', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa drużyny', max_length=40, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='surface',
            field=models.CharField(choices=[('nt', 'murawa naturalna'), ('at', 'murawa sztuczna'), ('fs', 'płaska powierzchnia')], default='nt'),
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Temat treningu', max_length=100, null=True)),
                ('goals', models.CharField(blank=True, help_text='Cele', max_length=100, null=True)),
                ('rules', models.CharField(blank=True, help_text='Zasady ', max_length=100, null=True)),
                ('actions', models.CharField(blank=True, help_text='Działania', max_length=100, null=True)),
                ('start_datatime', models.DateTimeField(blank=True, help_text='Data i godzina rozpoczęcia', null=True)),
                ('end_datatime', models.DateTimeField(blank=True, help_text='Data i godzina zakończenia', null=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.place')),
                ('player', models.ManyToManyField(through='clubs.Attendance', to='clubs.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.team')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.player'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='training',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.training'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('player', 'training'), name='unique_player_training_attendence'),
        ),
    ]
