# Generated by Django 4.2.7 on 2023-11-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_season_player_season_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='player',
            field=models.ManyToManyField(blank=True, to='clubs.player'),
        ),
        migrations.AlterField(
            model_name='season',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.team'),
        ),
    ]
