# Generated by Django 4.2.7 on 2023-11-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_season_player_alter_season_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
