# Generated by Django 4.2.7 on 2023-11-13 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0009_usersclub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(choices=[('D', 'UEFA D'), ('C_F', 'UEFA FUTSAL C'), ('C', 'UEFA C'), ('B_F', 'UEFA FUTSAL B'), ('B_GK', 'UEFA GOALKEEPER B'), ('B', 'UEFA B'), ('B_EY', 'UEFA B ELITE YOUTH'), ('A_GK', 'UEFA GOALKEEPER A'), ('A', 'UEFA A'), ('A_EY', 'UEFA A ELITE YOUTH'), ('PRO', 'UEFA PRO')], default='null', help_text='Uprawnienia', null=True)),
                ('license_expiry_date', models.DateField(blank=True, help_text='Data wygaśnięcia uprawnień', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa dofinansowania', max_length=100)),
                ('link', models.URLField(blank=True, help_text='Link do oferty', null=True)),
                ('founder', models.CharField(help_text='Nazwa fundacji/organizacji', max_length=100, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maksymalna kwota dofinansowania', max_digits=15, null=True)),
                ('start_of_application', models.DateField(blank=True, help_text='Początek przyjmowania zgłoszeń', null=True)),
                ('end_of_application', models.DateField(help_text='Koniec przyjmowania zgłoszeń', null=True)),
                ('date_of_application', models.DateField(blank=True, help_text='Data wysłania zgłoszenia', null=True)),
                ('end_of_processing', models.DateField(help_text='Koniec przyjmowania zgłoszeń', null=True)),
                ('description', models.TextField(blank=True, help_text='Opis o co wnioskowano w zadaniu i na jaką kwotę', null=True)),
                ('grant_awarded', models.BooleanField(blank=True, help_text='Dofinansowanie przyznane', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='joining_date',
            field=models.DateField(auto_now=True, help_text='Data dołącznia do klubu', null=True),
        ),
        migrations.CreateModel(
            name='UsersGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.grant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeover_date', models.DateField(help_text='Data przejęcia druzyny', null=True)),
                ('leaving_date', models.DateField(blank=True, help_text='Data odejścia z druzyny', null=True)),
                ('role_in_team', models.CharField(choices=[('I', 'PIERWSZY TRENER'), ('II', 'DRUGI TRENER'), ('AS', 'ASYSTENT TRENERA'), ('AN', 'TRENER ANALITYK'), ('GK', 'TRENER BRAMKARZY'), ('PM', 'TRENER PRZYGOTOWANIA MOTORYCZNEGO'), ('TM', 'TRENER MENTALNY'), ('TR', 'TRENER ')], default='null', help_text='Funkcja w drużynie', null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.coach')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.team')),
            ],
        ),
    ]
