# Generated by Django 4.2.7 on 2023-11-13 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0011_grant_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mezocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa mezocyklu', max_length=60, null=True)),
                ('weeks', models.PositiveSmallIntegerField(help_text='Ile trwa tygodni', null=True)),
                ('trainings_per_week', models.PositiveSmallIntegerField(help_text='Ilość treningów tygodniowo', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training_in_mezocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(help_text='Numer tygodnia', null=True)),
                ('training_number', models.PositiveSmallIntegerField(help_text='Numer treningu', null=True)),
                ('topic', models.CharField(help_text='Temat treningu', max_length=100, null=True)),
                ('goals', models.CharField(blank=True, help_text='Cele', max_length=100, null=True)),
                ('rules', models.CharField(blank=True, help_text='Zasady ', max_length=100, null=True)),
                ('actions', models.CharField(blank=True, help_text='Działania', max_length=100, null=True)),
                ('duration', models.PositiveSmallIntegerField(help_text='Czas trwania', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa zadania', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Opis zadania', null=True)),
                ('added', models.DateField(auto_now=True, help_text='Data dodania')),
                ('deadline', models.DateField(blank=True, help_text='Deadline', null=True)),
                ('status', models.CharField(choices=[('TO DO', 'Do zrobienia'), ('IN PROGRES', 'W trakcie'), ('DONE', 'Zrobione')], default='TO DO')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
