# Generated by Django 4.2.7 on 2023-11-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_rename_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
        ),
    ]
