# Generated by Django 4.2.7 on 2023-11-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_training_in_mezocycle_mezocycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_in_mezocycle',
            name='Mezocycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.mezocycle'),
        ),
    ]
