# Generated by Django 4.2.7 on 2023-11-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_alter_training_in_mezocycle_mezocycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_in_mezocycle',
            old_name='Mezocycle',
            new_name='mezocycle',
        ),
        migrations.AlterField(
            model_name='coach',
            name='license',
            field=models.CharField(choices=[('UEFA D', 'UEFA D'), ('UEFA FUTSAL C', 'UEFA FUTSAL C'), ('UEFA C', 'UEFA C'), ('UEFA FUTSAL B', 'UEFA FUTSAL B'), ('UEFA GOALKEEPER B', 'UEFA GOALKEEPER B'), ('UEFA B', 'UEFA B'), ('UEFA B ELITE YOUTH', 'UEFA B ELITE YOUTH'), ('UEFA GOALKEEPER A', 'UEFA GOALKEEPER A'), ('UEFA A', 'UEFA A'), ('UEFA A ELITE YOUTH', 'UEFA A ELITE YOUTH'), ('UEFA PRO', 'UEFA PRO')], default='null', help_text='Uprawnienia', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='addres',
            field=models.CharField(blank=True, help_text='Adres obiektu', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='added',
            field=models.DateTimeField(auto_now=True, help_text='Data dodania'),
        ),
        migrations.AlterField(
            model_name='teamscoach',
            name='role_in_team',
            field=models.CharField(choices=[('PIERWSZY TRENER', 'PIERWSZY TRENER'), ('DRUGI TRENER', 'DRUGI TRENER'), ('ASYSTENT TRENERA', 'ASYSTENT TRENERA'), ('TRENER ANALITYK', 'TRENER ANALITYK'), ('TRENER BRAMKARZY', 'TRENER BRAMKARZY'), ('TRENER PRZYGOTOWANIA MOTORYCZNEGO', 'TRENER PRZYGOTOWANIA MOTORYCZNEGO'), ('TRENER MENTALNY', 'TRENER MENTALNY'), ('TRENER', 'TRENER ')], default='null', help_text='Funkcja w drużynie', null=True),
        ),
        migrations.AddConstraint(
            model_name='coach',
            constraint=models.UniqueConstraint(fields=('user', 'license'), name='unique_user_license'),
        ),
        migrations.AddConstraint(
            model_name='mezocycle',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_user_mezocycle'),
        ),
        migrations.AddConstraint(
            model_name='mezocycle',
            constraint=models.UniqueConstraint(fields=('name', 'team'), name='unique_team_mezocycle'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('name', 'team'), name='unique_team_season'),
        ),
        migrations.AddConstraint(
            model_name='training_in_mezocycle',
            constraint=models.UniqueConstraint(fields=('mezocycle', 'week_number', 'training_number'), name='unique_mezocycle_training'),
        ),
        migrations.AddConstraint(
            model_name='usersclub',
            constraint=models.UniqueConstraint(fields=('user', 'club'), name='unique_user_club'),
        ),
        migrations.AddConstraint(
            model_name='usersgrant',
            constraint=models.UniqueConstraint(fields=('user', 'grant'), name='unique_user_grant'),
        ),
    ]
