# Generated by Django 4.2.7 on 2023-11-19 17:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0019_rename_coach_coachingstaff_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoachingStaff',
            new_name='Coaching_Staff',
        ),
        migrations.RenameModel(
            old_name='TeamsCoachingStaff',
            new_name='Teams_Coaching_Staff',
        ),
        migrations.RenameField(
            model_name='teams_coaching_staff',
            old_name='coachingStaff',
            new_name='coaching_Staff',
        ),
    ]
