# Generated by Django 4.2.7 on 2023-11-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_rename_coachingstaff_coaching_staff_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams_Coaching_Staff',
            new_name='TeamsCoaching_Staff',
        ),
    ]
