# Generated by Django 4.2.7 on 2023-11-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_rename_teams_coaching_staff_teamscoaching_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='date_of_start',
            field=models.DateField(blank=True, help_text='Data zakończenia sezonu', null=True),
        ),
    ]
