# Generated by Django 4.2.7 on 2023-11-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0022_season_date_of_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='date_of_end',
            field=models.DateField(blank=True, help_text='Data zakończenia sezonu', null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='date_of_start',
            field=models.DateField(help_text='Data rozpoczęcia sezonu', null=True),
        ),
    ]
