# Generated by Django 4.2.7 on 2023-11-21 19:51

import clubs.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0023_season_date_of_end_alter_season_date_of_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='yeor_of_foundation',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rok założenia klubu', null=True, validators=[django.core.validators.MinValueValidator(1800), clubs.models.max_value_current_year]),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(blank=True, choices=[('UEFA D', 'UEFA D'), ('UEFA FUTSAL C', 'UEFA FUTSAL C'), ('UEFA C', 'UEFA C'), ('UEFA FUTSAL B', 'UEFA FUTSAL B'), ('UEFA GOALKEEPER B', 'UEFA GOALKEEPER B'), ('UEFA B', 'UEFA B'), ('UEFA B ELITE YOUTH', 'UEFA B ELITE YOUTH'), ('UEFA GOALKEEPER A', 'UEFA GOALKEEPER A'), ('UEFA A', 'UEFA A'), ('UEFA A ELITE YOUTH', 'UEFA A ELITE YOUTH'), ('UEFA PRO', 'UEFA PRO')], default='null', help_text='Uprawnienia', null=True)),
                ('license_expiry_date', models.DateField(blank=True, help_text='Data wygaśnięcia uprawnień', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
