# Generated by Django 4.2.7 on 2023-11-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0024_alter_club_yeor_of_foundation_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='yeor_of_foundation',
            new_name='year_of_foundation',
        ),
    ]
