# Generated by Django 4.2.7 on 2023-11-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_rename_yeor_of_foundation_club_year_of_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersclub',
            name='admin',
            field=models.BooleanField(default=False, help_text='Czy jest administratorem klubu'),
        ),
        migrations.AddField(
            model_name='usersclub',
            name='coach',
            field=models.BooleanField(default=False, help_text='Czy jest trenerem w klubie'),
        ),
        migrations.AddField(
            model_name='usersclub',
            name='employee',
            field=models.BooleanField(default=False, help_text='Czy jest pracownikiem w klubie'),
        ),
        migrations.AddField(
            model_name='usersclub',
            name='training_coordinator',
            field=models.BooleanField(default=False, help_text='Czy jest koordynatorem szkolenia w klubie'),
        ),
    ]
