# Generated by Django 4.2.7 on 2023-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0027_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersclub',
            name='accepted',
            field=models.BooleanField(blank=True, default=None, help_text='Czy użytkownik zaakceptował zaproszenie'),
        ),
    ]
