# Generated by Django 4.2.7 on 2023-11-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0031_alter_usersclub_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('U6', 'JUNIOR G2'), ('U14', 'JUNIOR C2'), ('U11', 'JUNIOR E1'), ('U12', 'JUNIOR D2'), ('U13', 'JUNIOR D1'), ('U18', 'JUNIOR A2'), ('U19', 'JUNIOR A1'), ('U7', 'JUNIOR G1'), ('U8', 'JUNIOR F2'), ('U9', 'JUNIOR F1'), ('U10', 'JUNIOR E2'), ('U15', 'JUNIOR C1'), ('U16', 'JUNIOR B2'), ('SENIOR', 'SENIOR'), ('U17', 'JUNIOR B1')], default=None),
        ),
    ]
