# Generated by Django 4.2.7 on 2023-11-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0032_team_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('SENIOR', 'SENIOR'), ('U14', 'JUNIOR C2'), ('U8', 'JUNIOR F2'), ('U13', 'JUNIOR D1'), ('U11', 'JUNIOR E1'), ('U7', 'JUNIOR G1'), ('U17', 'JUNIOR B1'), ('U15', 'JUNIOR C1'), ('U16', 'JUNIOR B2'), ('U10', 'JUNIOR E2'), ('U9', 'JUNIOR F1'), ('U18', 'JUNIOR A2'), ('U19', 'JUNIOR A1'), ('U6', 'JUNIOR G2'), ('U12', 'JUNIOR D2')], default=None),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'club'), name='unique_team_name_in_club'),
        ),
    ]
