# Generated by Django 4.2.7 on 2023-11-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0033_alter_team_category_team_unique_team_name_in_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(help_text='Imię', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='surname',
            field=models.CharField(help_text='Nazwisko', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('U9', 'JUNIOR F1'), ('U7', 'JUNIOR G1'), ('U12', 'JUNIOR D2'), ('U11', 'JUNIOR E1'), ('U15', 'JUNIOR C1'), ('U18', 'JUNIOR A2'), ('U19', 'JUNIOR A1'), ('SENIOR', 'SENIOR'), ('U14', 'JUNIOR C2'), ('U16', 'JUNIOR B2'), ('U17', 'JUNIOR B1'), ('U13', 'JUNIOR D1'), ('U6', 'JUNIOR G2'), ('U10', 'JUNIOR E2'), ('U8', 'JUNIOR F2')], default=None),
        ),
    ]
