# Generated by Django 4.2.7 on 2023-11-30 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0034_alter_player_name_alter_player_surname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamscoaching_staff',
            name='coaching_Staff',
        ),
        migrations.AddField(
            model_name='teamscoaching_staff',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('U15', 'JUNIOR C1'), ('U11', 'JUNIOR E1'), ('U12', 'JUNIOR D2'), ('U17', 'JUNIOR B1'), ('SENIOR', 'SENIOR'), ('U19', 'JUNIOR A1'), ('U8', 'JUNIOR F2'), ('U18', 'JUNIOR A2'), ('U13', 'JUNIOR D1'), ('U16', 'JUNIOR B2'), ('U14', 'JUNIOR C2'), ('U7', 'JUNIOR G1'), ('U10', 'JUNIOR E2'), ('U6', 'JUNIOR G2'), ('U9', 'JUNIOR F1')], default=None),
        ),
    ]
