# Generated by Django 4.2.7 on 2023-11-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0035_remove_teamscoaching_staff_coaching_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='date_of_end',
            field=models.DateField(help_text='Data zakończenia sezonu', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('U6', 'JUNIOR G2'), ('U14', 'JUNIOR C2'), ('U7', 'JUNIOR G1'), ('U18', 'JUNIOR A2'), ('U8', 'JUNIOR F2'), ('SENIOR', 'SENIOR'), ('U9', 'JUNIOR F1'), ('U19', 'JUNIOR A1'), ('U11', 'JUNIOR E1'), ('U17', 'JUNIOR B1'), ('U12', 'JUNIOR D2'), ('U13', 'JUNIOR D1'), ('U15', 'JUNIOR C1'), ('U16', 'JUNIOR B2'), ('U10', 'JUNIOR E2')], default=None),
        ),
    ]
