# Generated by Django 4.2.7 on 2023-12-09 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0036_alter_season_date_of_end_alter_team_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='club',
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('U7', 'JUNIOR G1'), ('U12', 'JUNIOR D2'), ('U18', 'JUNIOR A2'), ('U19', 'JUNIOR A1'), ('U13', 'JUNIOR D1'), ('U15', 'JUNIOR C1'), ('SENIOR', 'SENIOR'), ('U6', 'JUNIOR G2'), ('U11', 'JUNIOR E1'), ('U10', 'JUNIOR E2'), ('U9', 'JUNIOR F1'), ('U16', 'JUNIOR B2'), ('U17', 'JUNIOR B1'), ('U14', 'JUNIOR C2'), ('U8', 'JUNIOR F2')], default=None),
        ),
        migrations.AddField(
            model_name='place',
            name='club',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='clubs.club'),
            preserve_default=False,
        ),
    ]
