# Generated by Django 4.2.7 on 2023-12-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0037_remove_place_club_alter_team_category_place_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='changing_rooms',
            field=models.BooleanField(blank=True, help_text='Sztanie', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='toilets',
            field=models.BooleanField(blank=True, help_text='Toalety', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('U13', 'JUNIOR D1'), ('U14', 'JUNIOR C2'), ('U10', 'JUNIOR E2'), ('U15', 'JUNIOR C1'), ('U16', 'JUNIOR B2'), ('U12', 'JUNIOR D2'), ('U9', 'JUNIOR F1'), ('U6', 'JUNIOR G2'), ('U8', 'JUNIOR F2'), ('U18', 'JUNIOR A2'), ('U17', 'JUNIOR B1'), ('SENIOR', 'SENIOR'), ('U7', 'JUNIOR G1'), ('U19', 'JUNIOR A1'), ('U11', 'JUNIOR E1')], default=None),
        ),
    ]
