# Generated by Django 4.2.7 on 2023-12-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0038_place_changing_rooms_place_toilets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('U12', 'JUNIOR D2'), ('U6', 'JUNIOR G2'), ('U15', 'JUNIOR C1'), ('U11', 'JUNIOR E1'), ('U19', 'JUNIOR A1'), ('U13', 'JUNIOR D1'), ('U17', 'JUNIOR B1'), ('U10', 'JUNIOR E2'), ('U14', 'JUNIOR C2'), ('U16', 'JUNIOR B2'), ('U8', 'JUNIOR F2'), ('U7', 'JUNIOR G1'), ('U9', 'JUNIOR F1'), ('U18', 'JUNIOR A2'), ('SENIOR', 'SENIOR')], default=None),
        ),
    ]
