# Generated by Django 4.2.7 on 2023-12-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0040_remove_training_team_alter_team_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_player_training_attendence',
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('U18', 'JUNIOR A2'), ('U13', 'JUNIOR D1'), ('U14', 'JUNIOR C2'), ('U11', 'JUNIOR E1'), ('U16', 'JUNIOR B2'), ('U15', 'JUNIOR C1'), ('U6', 'JUNIOR G2'), ('U9', 'JUNIOR F1'), ('U17', 'JUNIOR B1'), ('U19', 'JUNIOR A1'), ('SENIOR', 'SENIOR'), ('U8', 'JUNIOR F2'), ('U10', 'JUNIOR E2'), ('U7', 'JUNIOR G1'), ('U12', 'JUNIOR D2')], default=None),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('player', 'training')},
        ),
    ]
