# Generated by Django 4.2.7 on 2023-12-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0041_remove_attendance_unique_player_training_attendence_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('U8', 'JUNIOR F2'), ('U18', 'JUNIOR A2'), ('U14', 'JUNIOR C2'), ('U16', 'JUNIOR B2'), ('SENIOR', 'SENIOR'), ('U10', 'JUNIOR E2'), ('U12', 'JUNIOR D2'), ('U7', 'JUNIOR G1'), ('U15', 'JUNIOR C1'), ('U19', 'JUNIOR A1'), ('U6', 'JUNIOR G2'), ('U17', 'JUNIOR B1'), ('U9', 'JUNIOR F1'), ('U11', 'JUNIOR E1'), ('U13', 'JUNIOR D1')], default=None),
        ),
    ]
