# Generated by Django 4.2.7 on 2023-12-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0043_alter_attendance_player_alter_attendance_training_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('U15', 'JUNIOR C1'), ('U14', 'JUNIOR C2'), ('U11', 'JUNIOR E1'), ('U16', 'JUNIOR B2'), ('U6', 'JUNIOR G2'), ('U8', 'JUNIOR F2'), ('U7', 'JUNIOR G1'), ('U19', 'JUNIOR A1'), ('U17', 'JUNIOR B1'), ('U9', 'JUNIOR F1'), ('SENIOR', 'SENIOR'), ('U18', 'JUNIOR A2'), ('U13', 'JUNIOR D1'), ('U10', 'JUNIOR E2'), ('U12', 'JUNIOR D2')], default=None),
        ),
        migrations.CreateModel(
            name='ImplementedMezocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa mezocyklu', max_length=60, null=True)),
                ('weeks', models.PositiveSmallIntegerField(help_text='Ile trwa tygodni', null=True)),
                ('trainings_per_week', models.PositiveSmallIntegerField(help_text='Ilość treningów tygodniowo', null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.team')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='implemented_mezocycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.implementedmezocycle'),
        ),
        migrations.AddConstraint(
            model_name='implementedmezocycle',
            constraint=models.UniqueConstraint(fields=('name', 'team'), name='unique_team_implemented_mezocycle'),
        ),
    ]
