# Generated by Django 4.2.7 on 2023-12-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0044_alter_team_category_implementedmezocycle_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mezocycle',
            name='unique_user_mezocycle',
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('U8', 'JUNIOR F2'), ('U19', 'JUNIOR A1'), ('U15', 'JUNIOR C1'), ('U17', 'JUNIOR B1'), ('U10', 'JUNIOR E2'), ('U13', 'JUNIOR D1'), ('U6', 'JUNIOR G2'), ('U14', 'JUNIOR C2'), ('U16', 'JUNIOR B2'), ('U18', 'JUNIOR A2'), ('U12', 'JUNIOR D2'), ('U11', 'JUNIOR E1'), ('U7', 'JUNIOR G1'), ('SENIOR', 'SENIOR'), ('U9', 'JUNIOR F1')], default=None),
        ),
    ]
