# Generated by Django 4.2.7 on 2024-01-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0045_remove_mezocycle_unique_user_mezocycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_data',
            name='extranet',
            field=models.CharField(blank=True, help_text='nr extranet', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='player_data',
            name='pesel',
            field=models.CharField(blank=True, help_text='Pesel', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('U6', 'JUNIOR G2'), ('U7', 'JUNIOR G1'), ('U8', 'JUNIOR F2'), ('U9', 'JUNIOR F1'), ('U10', 'JUNIOR E2'), ('U11', 'JUNIOR E1'), ('U12', 'JUNIOR D2'), ('U13', 'JUNIOR D1'), ('U14', 'JUNIOR C2'), ('U15', 'JUNIOR C1'), ('U16', 'JUNIOR B2'), ('U17', 'JUNIOR B1'), ('U18', 'JUNIOR A2'), ('U19', 'JUNIOR A1'), ('SENIOR', 'SENIOR')], default=None),
        ),
    ]
