# Generated by Django 4.2.7 on 2024-01-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0046_alter_player_data_extranet_alter_player_data_pesel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(help_text='Nazwa Sprzętu', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='addres',
            field=models.CharField(help_text='Adres obiektu', max_length=100, null=True),
        ),
    ]
