# Generated by Django 4.2.7 on 2024-01-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0047_alter_equipment_name_alter_place_addres'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='motoric_goals',
            field=models.CharField(blank=True, help_text='Cele motoryczne', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='training_in_mezocycle',
            name='motoric_goals',
            field=models.CharField(blank=True, help_text='Cele motoryczne', max_length=100, null=True),
        ),
    ]
